### ISSUE TITLE
发送图片报错，图片是发出去了，但是水印没加上去

### ISSUE THREAD

**Issue by Nenot233** [X-Skirt-X/nonebot-plugin-watermarker#1]
05-03 14:34:52 [ERROR] nonebot | Error when running CallingAPI hook. Running cancelled!
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1503, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: '\\D'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 174, in send
    return await bot.send_msg(**params)
 File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\internal\adapter\bot.py", line 83, in call_api
    await asyncio.gather(*coros)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_watermarker\__init__.py", line 36, in _handle
    if image := str2img(file):
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_watermarker\fuctions.py", line 32, in str2img
    bytes = urllib.request.urlopen(string).read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1481, in file_open
    return self.open_local_file(req)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1520, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 2] 系统找不到指定的文件。: '\\D'>

**Comment by Nenot233** [comment]
发现了本地图片都不行，生成的图片部分可以

**Comment by ChenXu233** [comment]
已经重新整过了,更新一下试试

**Comment by ChenXu233** [comment]
相关问题已由解决,可以重新安装以修复.
实际问题详情可以看 #2
